services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopping_cart
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - db
    restart: unless-stopped

  shopping-cart-backend:
    container_name: shopping-cart-backend
    image: drishtigoda/shopping-cart-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shopping_cart
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
